# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Seher Gürel
title: Bilgisayar Mühendisi
phone: 05412965780
email: shrgurel@gmail.com
website: https://shrgrl.github.io/portfolio/

# Social links
twitter_username: sehergurel
github_username:  shrgrl
# dribbble_username: jekyll
facebook_username: seher.gurel2
# flickr_username: jekyll
instagram_username: sehergurell
linkedin_username: sehergurel
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title: Hakkımda
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Merhaba, ben Seher Gürel. 23 yaşındayım, Giresun'da doğdum. Lisans eğitimimi Erzurum'da, Atatürk Üniversitesi, Bilgisayar Mühendisliği Bölümü'nde tamamladım.
  Hedefim, mükemmel ve aranan bir mühendis olmak için yararlı ve yeni deneyimler kazanmak ve bu kazanımlarımı ülkeme faydalı olacak şekilde kullanmaktır. <br><br>
  <b>Genel yeteneklerim:</b> &nbsp; &nbsp; &nbsp; <mark>Java</mark> <mark>JavaScript</mark> <mark>MongoDB</mark> <mark>NodeJS</mark> 
  <mark>C/C++</mark> <mark>HTML</mark> <mark>Arduino</mark> <mark>Python</mark>
  <br><br>
  <b>Diller:</b> &nbsp; &nbsp; &nbsp; <mark>İNGİLİZCE &starf; &starf; &starf; &star; &star;</mark> <mark>ALMANCA &starf; &star; &star; &star; &star;</mark>

# Projects Section
projects_title: Projelerim

# Experience Section
experience_title: Tecrübelerim

# Education Section
educaton_title: Akademik Bilgilerim

# More Section
more_title: İlgi Alanlarım ve Hobilerim
more_content: | # this will include new lines to allow paragraphs
  Programcılık, yazılım, bilgisayar mühendisliğine olan ilgimin yanı sıra, diğer ilgi alanlarım ve hobilerim:
  <ul>
    <li>Farklı kültürler tanımak</li>
    <li>Müzik dinlemek</li>
    <li>Kitap okumak</li>
    <li>Resim yapmak</li>
    <li>Dağcılık</li>
    <li>Buz Pateni</li>
    <li>Satranç...</li>
  </ul>

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
