# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Seher Gürel Mousselli
title: Abap|Fiori Developer
email: shrgurel@gmail.com
website: http://sehergurel.com/

# Social links
twitter_username: sehergurel
github_username:  shrgrl
# dribbble_username: jekyll
facebook_username: seher.gurel2
# flickr_username: jekyll
instagram_username: sehergurell
linkedin_username: sehergurel
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title: Hakkımda
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Merhaba, ben Seher Gürel Mousselli. 1996 yılında, Giresun'da doğdum. Lisans eğitimimi Erzurum'da, Atatürk Üniversitesi, Bilgisayar Mühendisliği Bölümü'nde tamamladım.
  Eğitim hayatımda edindiğim bilgilerin üstüne her geçen gün yenilerini ekleyerek, süreklilik içinde kendimi geliştirmeye devam ediyorum.
  Teknolojiyi en doğru şekilde kullanarak günlük yaşamda ihtiyaçları karşılayacak ya da eğlendirici, öğretici ürünler geliştirip insanlık adına faydalı işler yapmayı hedefliyorum.<br><br>
  <b>Genel yeteneklerim:</b> &nbsp; &nbsp; &nbsp; <mark>ABAP</mark> <mark>SAPUI5</mark> <mark>Java</mark> <mark>JavaScript</mark> <mark>MongoDB</mark> <mark>NodeJS</mark> 
  <mark>Redis Cache</mark> <mark>C/C++</mark> <mark>HTML</mark> <mark>Python</mark> <mark>OpenGL</mark> <mark>OpenCV</mark>
  <mark>Raspberry Pi</mark> <mark>Arduino UNO</mark> <mark>Android Studio</mark> <mark>Fritzing</mark> <mark>StarUML</mark>
  <br><br>
  <b>Diller:</b> &nbsp; &nbsp; &nbsp; <mark>İNGİLİZCE &starf; &starf; &starf; &star; &star;</mark> <mark>ALMANCA &starf; &star; &star; &star; &star;</mark>
  <br><br>
  <b>Sürücü Belgesi:</b> &nbsp; &nbsp; &nbsp; <mark>B Sınıfı Sürücü Belgesi</mark>

# Projects Section
projects_title: Projelerim

# Experience Section
experience_title: Tecrübelerim

# Education Section
educaton_title: Akademik Bilgilerim

# More Section
more_title: İlgi Alanlarım ve Hobilerim
more_content: | # this will include new lines to allow paragraphs
  Programcılık, yazılım, bilgisayar mühendisliğine olan ilgimin yanı sıra, diğer ilgi alanlarım ve hobilerim:
  <ul>
    <li>Farklı kültürler tanımak</li>
    <li>Müzik dinlemek</li>
    <li>Kitap okumak</li>
    <li>Resim yapmak</li>
    <li>Dağcılık</li>
    <li>Buz Pateni</li>
    <li>Satranç,</li>
    <li>Yazı ve Şiir Yazmak...</li>
  </ul>

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
